##############################################
###### Aggregate Room Occupancy Sensors ######
##############################################

#
## These binary sensors aggregate all sensors in a room that signal occupancy.
## Occupancy expires x minutes after the delay_off defined for the sensor.
#

- platform: template
  sensors:

    lorens_room_occupancy_aggregate:
      friendly_name: "Loren's Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.lorens_room_motion_sensor', 'on')
             or is_state('binary_sensor.lorens_room_bluetooth_device_present', "on") }}

    lorens_bathroom_occupancy_aggregate:
      friendly_name: "Loren's Bathroom Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.lorens_bathroom_motion_sensor', 'on') }}

    ryans_room_occupancy_aggregate:
      friendly_name: "Ryan's Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.ryans_room_motion_sensor', 'on')
             or is_state('binary_sensor.ryans_room_motion_sensor_2', 'on') }}

    ryans_bathroom_occupancy_aggregate:
      friendly_name: "Ryan's Bathroom Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.ryans_bathroom_motion_sensor', 'on') }}

  # backyard_occupancy_aggregate:
  #    friendly_name: "Backyard Occupancy Sensor"
  #    device_class: occupancy
  #    value_template: #No sensors available yet

    family_room_occupancy_aggregate:
      friendly_name: "Family Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
         {{ is_state('binary_sensor.family_room_motion_sensor', 'on')
         or is_state('binary_sensor.family_room_motion_sensor_2', 'on')
         or is_state('binary_sensor.family_room_presence', 'on') }}

    garage_occupancy_aggregate:
      friendly_name: "Garage Occupancy Sensor"
      device_class: occupancy
      value_template: >-
         {{ is_state('binary_sensor.garage_motion_sensor', 'on') }}

    hallway_occupancy_aggregate:
      friendly_name: "Hallway Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.hallway_motion_sensor', 'on') }}

    kitchen_occupancy_aggregate:
      friendly_name: "Kitchen Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.kitchen_motion_sensor', 'on')
          or is_state('binary_sensor.kitchen_motion_sensor_2', 'on') }}

    livingroom_occupancy_aggregate:
      friendly_name: "Living Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.living_room_occupancy', "on")
             or is_state('binary_sensor.living_room_motion_sensor', "on" )
             or is_state('binary_sensor.living_room_motion_sensor_2', "on" )
             or is_state('binary_sensor.living_room_motion_sensor_3', "on" )
             or is_state('binary_sensor.living_room_presence', "on" ) }}

    upstairs_hallway_occupancy_aggregate:
      friendly_name: "Upstairs Hallway Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.upstairs_hallway_motion_sensor', 'on') }}

    office_occupancy_aggregate:
      friendly_name: "Office Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.office_motion_sensor', 'on') }}

    simulator_occupancy_aggregate:
      friendly_name: "Simulator Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.simulator_motion_sensor', 'on') }}

###############################
##### Low Battery Sensors #####
###############################

###################################
##### Binary Sensor Platforms #####
###################################

- platform: hydrawise

- platform: aarlo
  monitored_conditions:
  - motion
  - sound
