##############################################
###### Aggregate Room Occupancy Sensors ######
##############################################

- platform: template
  sensors:

##### People's Rooms #####

    lorens_room_occupancy_aggregate:
      friendly_name: "Loren's Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.lorens_room_motion_sensor', 'on')
             or is_state('binary_sensor.lorens_room_bluetooth_device_present', "on") }}

    ryans_room_occupancy_aggregate:
      friendly_name: "Ryan's Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.ryans_desk_motion_sensor', 'on')
             or is_state('binary_sensor.ryans_room_motion_sensor', 'on')
             or is_state('binary_sensor.ryans_room_bluetooth_device_present', "on") }}

    ryans_bathroom_occupancy_aggregate:
      friendly_name: "Ryan's Bathroom Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.ryans_bathroom_motion_sensor', 'on')
             or is_state('binary_sensor.ryans_bathroom_bluetooth_device_present', "on") }} 

##### Shared Rooms #####

  # backyard_occupancy_aggregate:
  #    friendly_name: "Backyard Occupancy Sensor"
  #    device_class: occupancy
  #    value_template: #No sensors available yet

  # family_room_occupancy_aggregate:
  #   friendly_name: "Family Room Occupancy Sensor"
  #    device_class: occupancy
  #    value_template: #No sensors available yet

  # garage_occupancy_aggregate:
  #    friendly_name: "Garage Occupancy Sensor"
  #    device_class: occupancy
  #    value_template: #No sensors available yet

    hallway_occupancy_aggregate:
      friendly_name: "Hallway Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.hallway_motion_sensor', 'on') }}

    kitchen_occupancy_aggregate:
      friendly_name: "Kitchen Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.kitchen_motion_sensor', 'on')
             or is_state('binary_sensor.kitchen_bluetooth_device_present', "on") }}

    livingroom_occupancy_aggregate:
      friendly_name: "Living Room Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.living_room_occupancy', "on")
             or is_state('binary_sensor.livingroom_bluetooth_device_present', "on") }}

    upstairs_hallway_occupancy_aggregate:
      friendly_name: "Upstairs Hallway Occupancy Sensor"
      device_class: occupancy
      value_template: >-
          {{ is_state('binary_sensor.upstairs_hallway_motion_sensor', 'on') }}

###########################################################
###### Aggregate Bluetooth Presence Detector Sensors ######
###########################################################

    livingroom_bluetooth_device_present:
      friendly_name: "Living Room Bluetooth Device Present"
      device_class: presence
      value_template: >-
          {{ is_state('sensor.icetray_room_presence', 'Livingroom')
            or is_state('sensor.jordans_iphone_room_presence', "Livingroom")   
            or is_state('sensor.88_a4_79_b5_d2_a6_room_presence', "Livingroom") }}
    ryans_room_bluetooth_device_present:
      friendly_name: "Ryan's Room Bluetooth Device Present"
      device_class: presence
      value_template: >-
          {{ is_state('sensor.icetray_room_presence', "Ryan's Room")
            or is_state('sensor.jordans_iphone_room_presence', "Ryan's Room")
            or is_state('sensor.88_a4_79_b5_d2_a6_room_presence', "Ryan's Room") }}
    ryans_bathroom_bluetooth_device_present:
      friendly_name: "Ryan's Bathroom Bluetooth Device Present"
      device_class: presence
      value_template: >-
          {{ is_state('sensor.icetray_room_presence', "Ryan's Bathroom")
            or is_state('sensor.jordans_iphone_room_presence', "Ryan's Bathroom")
            or is_state('sensor.88_a4_79_b5_d2_a6_room_presence', "Ryan's Bathroom") }}
    lorens_room_bluetooth_device_present:
      friendly_name: "Loren's Room Bluetooth Device Present"
      device_class: presence
      value_template: >-
          {{ is_state('sensor.icetray_room_presence', "Loren's Room")
            or is_state('sensor.jordans_iphone_room_presence', "Loren's Room")
            or is_state('sensor.88_a4_79_b5_d2_a6_room_presence', "Loren's Room") }}
    kitchen_bluetooth_device_present:
      friendly_name: "Kitchen Bluetooth Device Present"
      device_class: presence
      value_template: >-
          {{ is_state('sensor.icetray_room_presence', "Kitchen")
            or is_state('sensor.jordans_iphone_room_presence', "Kitchen")
            or is_state('sensor.88_a4_79_b5_d2_a6_room_presence', "Kitchen") }}

################################            
##### Other Binary Sensors #####
################################

- platform: hydrawise

