# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  name: !secret home_name
  temperature_unit: F
  time_zone: America/Los_Angeles
  unit_system: imperial
  customize: !include customize.yaml

lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

intent:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml

discovery:
  ignore:
   - philips_hue

###############################
##### NATIVE INTEGRATIONS #####
###############################

vacuum: !include vacuums.yaml

cover: !include covers.yaml

light: !include lights.yaml

sensor: !include sensors.yaml

binary_sensor: !include binary_sensors.yaml

device_tracker: !include device_trackers.yaml

mqtt: !include mqtt.yaml

camera: !include cameras.yaml

alarm_control_panel: !include alarms.yaml

zone: !include zones.yaml

###############################
##### VENDOR INTEGRATIONS #####
###############################

aarlo: !include aarlo.yaml

tplink: !include tplink.yaml

ecobee:
  api_key: !secret ecobee_api_key

dyson: !include dyson.yaml

eufy:
  username: !secret eufy_user
  password: !secret eufy_password

  #influxdb: !include influxdb.yaml

webostv: !include webostv.yaml

wemo: !include wemo.yaml

homekit: !include homekit.yaml

sense:
  email: !secret sense_user
  password: !secret sense_password

sonos: !include sonos.yaml

hydrawise:
  access_token: !secret hydrawise_api_key

ios: !include ios.yaml

roomba: !include roomba.yaml

owntracks: !include owntracks.yaml

logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.binary_sensor: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.light: debug
    custom_components.aarlo.media_player: debug
    custom_components.aarlo.sensor: debug
    custom_components.aarlo.switch: debug
    pyaarlo: debug
