###########################
##### Light Platforms #####
###########################

- platform: aarlo

###########################
##### Template Lights #####
###########################

- platform: template
  lights:
    living_room_templated:
      friendly_name: "Living Room Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.livingroom
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.livingroom
    family_room_templated:
      friendly_name: "Family Room Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.family_room
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.family_room
    kitchen_templated:
      friendly_name: "Kitchen Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.kitchen
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.kitchen
    garage_templated:
      friendly_name: "Garage Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.garage
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.garage
    backyard_templated:
      friendly_name: "Backyard Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.backyard
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.backyard
    hallway_templated:
      friendly_name: "Hallway Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.hallway
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.hallway
    upstairs_hallway_templated:
      friendly_name: "Upstairs Hallway Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.upstairs_hallway
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.upstairs_hallway
    ryans_room_templated:
      friendly_name: "Ryan's Room Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.ryans_room
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.ryans_room
    ryans_bathroom_templated:
      friendly_name: "Ryan's Bathroom Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.ryans_bathroom
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.ryans_bathroom
    lorens_room_templated:
      friendly_name: "Loren's Room Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.lorens_room
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.lorens_room
    lorens_bathroom_templated:
      friendly_name: "Loren's Bathroom Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.lorens_bathroom
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.lorens_bathroom
    jordans_room_templated:
      friendly_name: "Jordan's Room Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.jordans_room
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.jordans_room
    office_templated:
      friendly_name: "Office Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.office
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.office
    simulator_templated:
      friendly_name: "Simulator Lights Templated"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.simulator
        data_template:
          brightness: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              50
            {% else %}
              255
            {% endif %}
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.simulator

########################
##### Light Groups #####
########################

- platform: group
  name: Kitchen Light South
  entities:
  - light.kitchen_light_south_1
  - light.kitchen_light_south_2

- platform: group
  name: Kitchen Light North
  entities:
    - light.kitchen_light_north_1
    - light.kitchen_light_north_2

- platform: group
  name: Pendant Light
  entities:
    - light.family_room_pendant_light_1
    - light.family_room_pendant_light_2
    - light.family_room_pendant_light_3
    - light.family_room_pendant_light_4

- platform: group
  name: Ryans Bathroom Mirror Light
  entities:
    - light.ryans_bathroom_mirror_light_1
    - light.ryans_bathroom_mirror_light_2
    - light.ryans_bathroom_mirror_light_3

- platform: group
  name: Glass Light
  entities:
    - light.glass_light_1
    - light.glass_light_2

##############################
##### Switch Conversions #####
##############################

- platform: switch
  name: Backyard Wall Lights
  entity_id: switch.backyard_wall_lights

- platform: switch
  name: Backyard Lights 1
  entity_id: switch.backyard_lights_1

- platform: switch
  name: Backyard Lights 2
  entity_id: switch.backyard_lights_2

- platform: switch
  name: Ryan's Floor Lamp
  entity_id: switch.ryans_floor_lamp

- platform: switch
  name: Spotlight
  entity_id: switch.spotlight

- platform: switch
  name: Loren's Floor Lamp
  entity_id: switch.lorens_floor_lamp

- platform: switch
  name: Ryan's Desk Lamp
  entity_id: switch.ryans_desk_lamp

- platform: switch
  name: Simulator Shop Light
  entity_id: switch.simulator_shop_light

- platform: switch
  name: Garage Lights
  entity_id: switch.garage_lights

- platform: switch
  name: Jordans Shop Light
  entity_id: switch.jordans_shop_light

- platform: switch
  name: Family Room Floor Lamp
  entity_id: switch.family_room_floor_lamp

- platform: switch
  name: Snake Lights
  entity_id: switch.snake_lights

- platform: switch
  name: Ceiling Lights
  entity_id: switch.ceiling_lights

- platform: switch
  name: Office Desk Lamp
  entity_id: switch.office_desk_lamp

- platform: switch
  name: Kitchen Lamp
  entity_id: switch.kitchen_lamp

- platform: switch
  name: Cabana
  entity_id: switch.cabana

- platform: switch
  name: Stair Light
  entity_id: switch.stair_light
