###########################
##### Light Platforms #####
###########################

#- platform: decora_wifi
#  username: !secret leviton_user
#  password: !secret leviton_password

- platform: aarlo

########################
##### Light Groups #####
########################

- platform: group
  name: Kitchen Light South
  entities:
  - light.kitchen_light_south_1
  - light.kitchen_light_south_2

- platform: group
  name: Kitchen Light North
  entities:
    - light.kitchen_light_north_1
    - light.kitchen_light_north_2

- platform: group
  name: Pendant Light
  entities:
    - light.family_room_pendant_light_1
    - light.family_room_pendant_light_2
    - light.family_room_pendant_light_3
    - light.family_room_pendant_light_4

- platform: group
  name: Ryans Bathroom Mirror Light
  entities:
    - light.ryans_bathroom_mirror_light_1
    - light.ryans_bathroom_mirror_light_2
    - light.ryans_bathroom_mirror_light_3

- platform: group
  name: Glass Light
  entities:
    - light.glass_light_1
    - light.glass_light_2

##############################
##### Switch Conversions #####
##############################

- platform: switch
  name: Backyard Lights 1
  entity_id: switch.backyard_lights

- platform: switch
  name: Backyard Lights 2
  entity_id: switch.backyard_lights_2

- platform: switch
  name: Ryan's Floor Lamp
  entity_id: switch.ryans_floor_lamp

- platform: switch
  name: Family Room Spotlight
  entity_id: switch.family_room_spotlight

- platform: switch
  name: Loren's Floor Lamp
  entity_id: switch.lorens_floor_lamp

- platform: switch
  name: Ryan's Desk Lamp
  entity_id: switch.ryans_desk_lamp

- platform: switch
  name: Loren's Shop Light
  entity_id: switch.lorens_shop_light

- platform: switch
  name: Garage Light 1
  entity_id: switch.garage_light_1

- platform: switch
  name: Garage Light 2
  entity_id: switch.garage_light_2

- platform: switch
  name: Jordans Shop Light
  entity_id: switch.jordans_shop_light

- platform: switch
  name: Family Room Shop Light
  entity_id: switch.family_room_shop_light

- platform: switch
  name: Snake Lights
  entity_id: switch.snake_lights

- platform: switch
  name: Backyard Wall Light 1
  entity_id: switch.backyard_wall_light_1

- platform: switch
  name: Backyard Wall Light 2
  entity_id: switch.backyard_wall_light_2

- platform: switch
  name: Ceiling Lights
  entity_id: switch.ceiling_lights

- platform: switch
  name: Office Desk Lamp
  entity_id: switch.office_desk_lamp
