###########################
###### House Sensors ######
###########################

- platform: min_max
  name: "House Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_temperature_aggregate
    - sensor.ryans_bathroom_temperature_aggregate
    - sensor.lorens_room_temperature_aggregate
    - sensor.upstairs_hallway_temperature_aggregate
    - sensor.jordans_room_temperature_aggregate
    - sensor.civics_room_temperature_aggregate
    - sensor.living_room_temperature_aggregate
    - sensor.family_room_temperature_aggregate
    - sensor.kitchen_temperature_aggregate
    - sensor.hallway_temperature_aggregate

- platform: min_max
  name: "House Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_humidity_aggregate
    - sensor.ryans_bathroom_humidity_aggregate
    - sensor.lorens_room_humidity_aggregate
    - sensor.upstairs_hallway_humidity_aggregate
    - sensor.jordans_room_humidity_aggregate
    - sensor.civics_room_humidity_aggregate
    - sensor.living_room_humidity_aggregate
    - sensor.family_room_humdity_aggregate
    - sensor.kitchen_humidity_aggregate
    - sensor.hallway_humidity_aggregate

- platform: min_max
  name: "House Air Quality"
  type: mean
  entity_ids:
    - air_quality.lorens_room_air_quality
    - air_quality.ryans_room_air_quality

###########################
###### Outside Sensors ######
###########################

- platform: min_max
  name: "Outside Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.backyard_temperature_aggregate

##############################
###### Upstairs Sensors ######
##############################

- platform: min_max
  name: "Upstairs Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_temperature_aggregate
    - sensor.ryans_bathroom_temperature_aggregate
    - sensor.lorens_room_temperature_aggregate
    - sensor.upstairs_hallway_temperature_aggregate

#################@@#############
###### Downstairs Sensors ######
###################@@###########

- platform: min_max
  name: "Downstairs Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.jordans_room_temperature_aggregate
    - sensor.civics_room_temperature_aggregate
    - sensor.living_room_temperature_aggregate
    - sensor.family_room_temperature_aggregate
    - sensor.kitchen_temperature_aggregate
    - sensor.hallway_temperature_aggregate

#################################
###### Living Room Sensors ######
#################################

- platform: min_max
  name: "Living Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.tempin                                   #ecowitt
    - sensor.living_room_temperature                  #ecobee
    - sensor.living_room_motion_sensor_temperature    #aqara
    - sensor.living_room_motion_sensor_temperature_2  #aqara
    - sensor.living_room_motion_sensor_temperature_3  #aquare
    - sensor.backyard_door_sensor_temperature

- platform: min_max
  name: "Livingroom Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.livingroom_humidity

- platform: min_max
  name: "Livingroom Light Sensor Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.livingroom_humidity

#################################
###### Family Room Sensors ######
#################################

- platform: min_max
  name: "Family Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
   - sensor.family_room_temperature                 #aqara
   - sensor.family_room_motion_sensor_temperature   #aqara
   - sensor.family_room_motion_sensor_temperature_2 #aqara
   - sensor.front_door_sensor_temperature           #aqara

- platform: min_max
  name: "Family Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.family_room_humidity

#############################
###### Kitchen Sensors ######
#############################

- platform: min_max
  name: "Kitchen Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.kitchen_temperature                  #ecobee
    - sensor.kitchen_motion_sensor_temperature    #aquara
    - sensor.kitchen_motion_sensor_temperature_2  #aqara

- platform: min_max
  name: "Kitchen Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.kitchen_humidity

#############################
###### Garage Sensors #######
#############################

- platform: min_max
  name: "Garage Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.garage_temperature                   #ecowitt -- converted from sensor.temp1
    - sensor.garage_motion_sensor_temperature     #aqara
    - sensor.garage_door_sensor_temperature       #aqara
    - sensor.garage_side_door_sensor_temperature  #aqara

- platform: min_max
  name: "Garage Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.garage_humidity

#############################
###### Backyard Sensors #####
#############################

- platform: min_max
  name: "Backyard Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.temp                         #ecowitt


- platform: min_max
  name: "Backyard Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.humidity

##############################
###### Frontyard Sensors #####
##############################

#############################
###### Hallway Sensors ######
#############################

- platform: min_max
  name: "Hallway Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.hallway_motion_sensor_temperature

# - platform: min_max
#  name: "Hallway Humidity Aggregate"
#  round_digits: 1
#  type: mean
#  entity_ids:
#    #No sensors available yet

######################################
###### Upstairs Hallway Sensors ######
######################################

- platform: min_max
  name: "Upstairs Hallway Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.upstairs_hallway_motion_sensor_temperature

# - platform: min_max
#  name: "Upstairs Hallway Humidity Aggregate"
#  round_digits: 1
#  type: mean
#  entity_ids:
#    #No sensors available yet

#################################
###### Ryan's Room Sensors ######
#################################

- platform: min_max
  name: "Ryans Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_motion_sensor_temperature   #hue
    - sensor.ryans_room_motion_sensor_temperature_2 #aqara
    - sensor.ryans_room_temperature_dyson

- platform: min_max
  name: "Ryans Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_humidity

##########################################
###### Ryan's Bathroom Room Sensors ######
##########################################

- platform: min_max
  name: "Ryans Bathroom Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_bathroom_motion_sensor_temperature #aqara

# - platform: min_max
#  name: "Ryans Bathroom Humidity Aggregate"
#  round_digits: 1
#  type: mean
#  entity_ids:
#    #No sensors available yet

##################################
###### Loren's Room Sensors ######
##################################

- platform: min_max
  name: "Lorens Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.lorens_room_temperature  #aqara

- platform: min_max
  name: "Lorens Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.lorens_room_humidity

######################################
###### Loren's Bathroom Sensors ######
######################################

- platform: min_max
  name: "Lorens Bathroom Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.lorens_bathroom_motion_sensor_temperature   #aqara

- platform: min_max
  name: "Lorens Bathroom Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.lorens_bathroom_humidity

###################################
###### Jordan's Room Sensors ######
###################################

- platform: min_max
  name: "Jordans Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.jordans_room_temperature     #aqara

- platform: min_max
  name: "Jordans Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.jordans_room_humidity

###############################
###### Simulator Sensors ######
###############################

- platform: min_max
  name: "Simulator Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.simulator_temperature   #aqara

- platform: min_max
  name: "Simulator Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.simulator_humidity

############################
###### Office Sensors ######
############################

- platform: min_max
  name: "Office Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.office_motion_sensor_temperature   #aqara

- platform: min_max
  name: "Office Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.office_humidity

#  Utilities #



##############################
###### Unit Conversions ######
##############################

- platform: template
  sensors:
    garage_temperature:
      friendly_name: "Garage Temperature"
      unit_of_measurement: '°F'
      value_template: "{{ states('sensor.temp1') }}"

    garage_humidity:
      friendly_name: "Garage Humidity"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.humidity1') }}"

    livingroom_humidity:
      friendly_name: "Livingroom Humidity"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.humidityin') }}"

    japanese_maple_soil_moisture:
      friendly_name: "Japanese Maple Soil Moisture"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.soilmoisture1') }}"

    front_yard_soil_moisture:
      friendly_name: "Front Yard Soil Moisture"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.soilmoisture2') }}"

    climate_kitchen_target_temperature:
      friendly_name: "Kitchen Thermostat Target Temperature"
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.kitchen', 'temperature') }}"

    global_dimmer_state:
          friendly_name: "Global Dimmer State"
          value_template: >-
            {% if is_state('input_boolean.global_dimmer', 'on') %}
              Dim
            {% else %}
              Bright
            {% endif %}

    home_alarm_state:
          friendly_name: "Home Alarm State"
          value_template: "{{ states('alarm_control_panel.ha_alarm') }}"

    arlo_alarm_state:
          friendly_name: "Home Alarm State"
          value_template: "{{ states('alarm_control_panel.aarlo_smarhub') }}"

#########################
##### Other Sensors #####
#########################

- platform: hydrawise

- platform: aarlo
  monitored_conditions:
  - total_cameras
  - last_capture
  - recent_activity
  - captured_today
  - battery_level
  - signal_strength

- platform: mqtt_room
  device_id: 123testid
  state_topic: "room-assistant/mqtt-room"