################################################
###### Aggregate Room Temperature Sensors ######
################################################

- platform: min_max
  name: "Upstairs Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_temperature_aggregate
    - sensor.ryans_bathroom_temperature_aggregate
    - sensor.lorens_room_temperature_aggregate
    - sensor.upstairs_hallway_temperature_aggregate

- platform: min_max
  name: "Downstairs Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.jordans_room_temperature_aggregate
    - sensor.civicss_room_temperature_aggregate
    - sensor.living_room_temperature_aggregate
    - sensor.family_room_temperature_aggregate
    - sensor.kitchen_temperature_aggregate
    - sensor.hallway_temperature_aggregate

- platform: min_max
  name: "House Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.upstairs_temperature_aggregate
    - sensor.downstairs_temperature_aggregate

- platform: min_max
  name: "Outside Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.backyard_temperature_aggregate

##########################
##### People's Rooms #####
##########################

- platform: min_max
  name: "Ryans Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_temperature_doorway
    - sensor.ryans_room_temperature

- platform: min_max
  name: "Ryans Bathroom Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_bathroom_temperature

- platform: min_max
  name: "Lorens Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.temperature_19

- platform: min_max
  name: "Jordans Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.temperature_25

- platform: min_max
  name: "Civics Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.temperature_34      

########################      
##### Shared Rooms #####
########################

- platform: min_max
  name: "Backyard Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.temp

- platform: min_max
  name: "Family Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
   - sensor.temperature_31

- platform: min_max
  name: "Garage Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.garage_temperature #This is the value converted from sensor.temp1

- platform: min_max
  name: "Hallway Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.hallway_temperature

- platform: min_max
  name: "Kitchen Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.kitchen_temperature

- platform: min_max
  name: "Living Room Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.tempin
    - sensor.living_room_temperature

- platform: min_max
  name: "Upstairs Hallway Temperature Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.upstairs_hallway_temperature

#############################################
###### Aggregate Room Humidity Sensors ######
#############################################

##########################      
##### People's Rooms #####
##########################

- platform: min_max
  name: "Ryans Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.ryans_room_humidity

# - platform: min_max
#  name: "Ryans Bathroom Humidity Aggregate"
#  round_digits: 1
#  type: mean
#  entity_ids:
#    #No sensors available yet

- platform: min_max
  name: "Lorens Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.humidity_20      

- platform: min_max
  name: "Jordans Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.humidity_26      

- platform: min_max
  name: "Civics Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.humidity_35

########################      
##### Shared Rooms #####
########################

- platform: min_max
  name: "Backyard Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.humidity

- platform: min_max
  name: "Family Room Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.humidity_32 

- platform: min_max
  name: "Garage Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.garage_humidity

# - platform: min_max
#  name: "Hallway Humidity Aggregate"
#  round_digits: 1
#  type: mean
#  entity_ids:
#    #No sensors available yet

- platform: min_max
  name: "Kitchen Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.kitchen_humidity

- platform: min_max
  name: "Livingroom Humidity Aggregate"
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.livingroom_humidity

# - platform: min_max
#  name: "Upstairs Hallway Humidity Aggregate"
#  round_digits: 1
#  type: mean
#  entity_ids:
#    #No sensors available yet

##############################
###### Unit Conversions ######
##############################

- platform: template
  sensors:          
    garage_temperature:
      friendly_name: "Garage Temperature"
      unit_of_measurement: '°F'
      value_template: "{{ states('sensor.temp1') }}"

    garage_humidity:
      friendly_name: "Garage Humidity"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.humidity1') }}"

    livingroom_humidity:
      friendly_name: "Livingroom Humidity"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.humidityin') }}"

    japanese_maple_soil_moisture:
      friendly_name: "Japanese Maple Soil Moisture"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.soilmoisture1') }}"

    front_yard_soil_moisture:
      friendly_name: "Front Yard Soil Moisture"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.soilmoisture2') }}"

#########################      
##### Other Sensors #####
#########################

- platform: hydrawise

- platform: aarlo
  monitored_conditions:
  - total_cameras
  - last_capture
  - recent_activity
  - captured_today
  - battery_level
  - signal_strength

